Traceback (most recent call last):
  File "<string>", line 1, in <module>
RuntimeError: Dora Runtime raised an error.

Caused by:
   0: main task failed
   1: failed to init an operator
   2: failed to init python operator
   3: Traceback (most recent call last):
        File "/home/mofaDora/mofa/python/examples/agentfight1/scripts/answer_agent1.py", line 5, in <module>
          from mofa.run.run_agent import run_dspy_or_crewai_agent
        File "/home/mofaDora/mofa/python/mofa/run/run_agent.py", line 3, in <module>
          import dspy
        File "/home/nkucodetest/miniconda3/lib/python3.12/site-packages/dspy/__init__.py", line 63, in <module>
          import dspy.teleprompt
        File "/home/nkucodetest/miniconda3/lib/python3.12/site-packages/dspy/teleprompt/__init__.py", line 5, in <module>
          from .finetune import *
        File "/home/nkucodetest/miniconda3/lib/python3.12/site-packages/dspy/teleprompt/finetune.py", line 28, in <module>
          os.makedirs(training_data_directory)
        File "<frozen os>", line 225, in makedirs

      FileExistsError: [Errno 17] File exists: 'local_cache/compiler'

Location:
    binaries/runtime/src/operator/python.rs:28:9
sagemaker.config INFO - Not applying SDK defaults from location: /etc/xdg/sagemaker/config.yaml
sagemaker.config INFO - Not applying SDK defaults from location: /home/nkucodetest/.config/sagemaker/config.yaml
